/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LIst: typeof import('./components/LIst.vue')['default']
    Movie: typeof import('./components/Movie.vue')['default']
    MovieCard: typeof import('./components/MovieCard.vue')['default']
    MovieDetails: typeof import('./components/MovieDetails.vue')['default']
    MovieSection: typeof import('./components/MovieSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./components/Row.vue')['default']
  }
}
